import OpenAI from 'openai';

// Fallback key if process.env.API_KEY is not defined
const API_KEY = process.env.API_KEY || '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';

const openai = new OpenAI({
    apiKey: API_KEY,
    baseURL: 'https://integrate.api.nvidia.com/v1',
    maxRetries: 1,
    timeout: 15000
});

const EMBEDDING_MODEL = "nvidia/nv-embed-v1";

/**
 * Generates embeddings for an array of text chunks.
 * @param {Array<{content: string, metadata: object}>} chunks - Chunks generated by the splitter
 * @returns {Promise<Array<{content: string, metadata: object, embedding: Array<number>}>>}
 */
export async function embedChunks(chunks) {
    if (!chunks || chunks.length === 0) {
        console.log("No chunks provided for embedding.");
        return [];
    }

    console.log(`\n🧠 Generating embeddings for ${chunks.length} chunks using model: ${EMBEDDING_MODEL}...`);
    const embeddedChunks = [];

    // Process in batches of 16 chunks to be safe and efficient
    const batchSize = 16;
    for (let i = 0; i < chunks.length; i += batchSize) {
        const batch = chunks.slice(i, i + batchSize);
        const inputs = batch.map(chunk => chunk.content);

        // Simple retry logic
        let retries = 3;
        while (retries > 0) {
            try {
                console.log(`  Processing batch ${Math.floor(i / batchSize) + 1}/${Math.ceil(chunks.length / batchSize)} (chunks ${i + 1} to ${Math.min(i + batchSize, chunks.length)})...`);
                const response = await openai.embeddings.create({
                    model: EMBEDDING_MODEL,
                    input: inputs,
                    encoding_format: "float",
                });

                // Associate embeddings back to chunks
                response.data.forEach((item, index) => {
                    embeddedChunks.push({
                        content: batch[index].content,
                        metadata: batch[index].metadata,
                        embedding: item.embedding
                    });
                });
                break; // success, break retry loop
            } catch (error) {
                retries--;
                console.error(`❌ Error embedding batch starting at index ${i}. Retries left: ${retries}. Error:`, error.message || error);
                if (retries === 0) {
                    throw error;
                }
                // Backoff delay before retry
                await new Promise(resolve => setTimeout(resolve, 1000));
            }
        }

        // Rate limit protection delay
        if (i + batchSize < chunks.length) {
            await new Promise(resolve => setTimeout(resolve, 200));
        }
    }

    console.log(`\n✅ Successfully generated embeddings for all ${embeddedChunks.length} chunks.`);
    return embeddedChunks;
}